[package]
name = "silly-rust-web-exp"
version = "0.1.0"
authors = ["Sean Martin <sean.martin@nyu.edu>"]

[dependencies]
nickel = "*"
# hyper = "*"
rand = "0.3"
rustc-serialize = "0.3.18"
# mustache = "*"
rusqlite = "0.8.0"
chrono = "*"
